### PR TITLE
Feature/update to polkadot 0.8.26 

### PR DESCRIPTION
**Pull request by AndreiNavoichyk**

### CODE REVIEW

**Review by MRamanenkau — DISMISSED** [review]

**Comment by MRamanenkau** [comment]
There is an unchecked point [1.6. Increase transaction version](https://www.notion.so/cere/Runtime-Update-Flow-0ebec7500a8444f7ad748fbaa3cc5cb2). Is it increased?

**Comment by MRamanenkau** [comment]
Also, looks like spec and impl versions are not updated

**Comment by MRamanenkau** [comment]
We don't need to merge [v0.8.26-1](https://github.com/paritytech/polkadot/compare/v0.8.26...v0.8.26-1) as it's polkadot specific update

**Review by MRamanenkau — APPROVED** [review]

**Review by Raid5594 — COMMENTED** [review]
Did we intend to update gitlab-ci and .maintain?

**Pull request merged**
